### ISSUE TITLE
Call button Dissappears if logged in trough Bitlbee

### ISSUE THREAD

**Issue by Vaskozl** [jitsi/jitsi#111]
If an xmpp account is logged in trough Bitlbee and Jitsi at the same time, friends are not able to perform a call as the call button is greyed out. Both local and friend client are running version 2.8 on GNU/Linux.

**Comment by bgrozev** [comment]
I suspect that this may be have been caused by https://github.com/jitsi/jitsi/commit/478a8ec46cc6c3ccebaadf965f9baa14e5975d1d or https://github.com/jitsi/jitsi/commit/4e5c881b236ec4be89199c06674b0dfa186d0513

**Comment by bgrozev** [comment]
If someone could confirm that reverting one (or both) of these fixes the problem, I'd push a revert to master (and figure out how to fix it later).

**Comment by 459below** [comment]
I just tried all combinations. Both commits separately and together. But reverting those changes did not seem to fix the issue. On two separate contacts running jitsi-android and chatsecure it didn't show the buttons reliably. Though it seems to help, if jitsi is using a higher priority, since that contact does at least initially show the buttons.

**Comment by 459below** [comment]
I've just tested jitsi-2.1.4590.10823 from back in 2013-04-30 and it behaves exactly the same. Meaning only the capabilities of the last signed in client on the side of the contact are being considered. Right now I'm currently looking into [OperationSetContactCapabilitiesJabberImpl](https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/impl/protocol/jabber/OperationSetContactCapabilitiesJabberImpl.java#L229). If I understand correctly, there should be code checking every single resource that contact has registered and use the capabilities of the resource supporting the most capabilities. However I did not find code similar to the one in [MetaUIContact](https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/impl/gui/main/contactlist/contactsource/MetaUIContact.java#L582) yet. Unfortunately contact.getResources() seems to be empty at this point.

**Comment by 459below** [comment]
So I took the list of resources straight from EntityCapsManager, since it seems way more reliable than contact.getResources(). This does actually work out pretty smoothly. I will test this a while and I will reference the commit, after I'm certain that it doesn't brake something.

**Comment by 459below** [comment]
https://github.com/459below/jitsi/commit/9dcb88b2a580243ac0e3b640b3f785ed16a5a705

I've been using this fix for some days. This shows the buttons appropriately and I haven't noticed any regressions. I have noticed a different issue mentioned in the commit message. But this seems to be a different pre-existing issue.

I suppose I should create a proper pull request in order to assess these changes, shouldn't I?
