### ISSUE TITLE
Java Compiled Problem

### ISSUE THREAD

**Issue by Lycoriso** [jitsi/jitsi#137]
GoogleAPIClientToken cannot be resolved to a variable	OAuth2TokenStore.java	/jitsi/src/net/java/sip/communicator/impl/googlecontacts	line 99

**Comment by cobratbq** [comment]
If you run 'ant clean make' once it should create the file for you.

**Comment by ibauersachs** [comment]
It would be easier if that file would exist with the default null values. If not, at least put the generated file to .gitignore so the working directory isn't shown as dirty.

**Comment by Lycoriso** [comment]
OK.

This file is auto-updated by build.xml in order to provide id and secret needed to use oauth2 for accessing google api.

**Comment by cobratbq** [comment]
@damencho would it work with build server configuration to make target "-pre-googlecontacts" a dependency for "clean" (instead of "compile")?

I think that would make more sense, make it more obvious for the developers. This is more a preparation of the source code (for compilation), rather than  it is a preparation of the build process itself, isn't it. And we can add the generated file to .gitignore list. Would that work for you?

**Comment by ibauersachs** [comment]
Huh? Can't you just do it the same way as impl.version.NightlyBuildID?

**Comment by damencho** [comment]
Hum, @lyubomir just give an idea, we can dump that file generation and read those values from default.properties and just make sure when those props are set we add those to the result file so we can package it in all OS. We just need to look in which ant target to update the.

**Comment by damencho** [comment]
I thought it is currently as NightlyBuildID?

**Comment by ibauersachs** [comment]
Almost: NightlyBuildID.java is always there and under source control with a default value. It's overwritten at "make"-time.

**Comment by damencho** [comment]
@cobratbq is it ok now?

**Comment by ibauersachs** [comment]
This was fixed in fba5aeba1ebeaea1942d949fe588d053b044e28a.
