### ISSUE TITLE
Jitsi doesn't start, message "NimbuzzAvatars"

### ISSUE THREAD

**Issue by Petrouchka** [jitsi/jitsi#162]
I installed JITSI jitsi-2.9.5477-x86.msi on fresh legal Windows XP Pro SP3 french version and jitsi-2.9.5477-x64.msi on Windows 7 Pro french version, in VirtualBox. After the installation, JITSI doesn't start, there's a message "NimbuzzAvatars" and nothing else.
![capture-1](https://cloud.githubusercontent.com/assets/3955499/10416190/e3651fbc-700b-11e5-8709-bc7436093c46.png)

**Comment by ibauersachs** [comment]
Delete the directory `%userprofile%\.sip-communicator`. Not sure how that got there, unless you ran the unit-tests from either Jitsi or libjitsi.

**Comment by Petrouchka** [comment]
Deleting the directory %userprofile%\.sip-communicator doesn't solve it. I restart with initial snapshot of Windows and had again the same problem.

**Comment by Petrouchka** [comment]
Same problem with 2.9.5478 version but jitsi-2.8.5426 stable version works fine.

**Comment by soratobukuroneko** [comment]
same problem on 2.10.5550

**Comment by cast-away** [comment]
same problem here on Kubuntu 19.10, how do I get the console output?

**Comment by cvincent** [comment]
Same issue as @soratobukuroneko, same console output, Pop!_OS 20.04.

**Comment by SpreadingRoots** [comment]
org.osgi.framework.BundleException: Unable to resolve net.java.sip.communicator.shutdowntimeout [76](R 76.0): missing requirement [net.java.sip.communicator.shutdowntimeout [76](R 76.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.configuration) [caused by: Unable to resolve org.jitsi.libjitsi [125](R 125.0): missing requirement [org.jitsi.libjitsi [125](R 125.0)] osgi.wiring.package; (osgi.wiring.package=com.sun.jna.ptr) [caused by: Unable to resolve com.sun.jna [88](R 88.0): missing requirement [com.sun.jna [88](R 88.0)] osgi.ee; (&(osgi.ee=JavaSE)(version=1.4.0))]] Unresolved requirements: [[net.java.sip.communicator.shutdowntimeout [76](R 76.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.configuration)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by CyberCam1969** [comment]
Has this been fixed or is it still ongoing?
I just install Jitsi Desktop 2.10.5550 on Debian 10 with the same issue.

**Comment by chepec** [comment]
This was quite a surprise. Is Jitsi desktop really broken on Debian/Ubuntu?

I'm not demanding a fix, but since the reports above indicate that Jitsi desktop Debian/Ubuntu has been broken for a few months, couldn't someone put a note on the [Jitsi desktop download page](https://desktop.jitsi.org/Main/Download.html) and save us some time?

I know that I can access Jitsi through the browser, and I suppose I will. But I thought the Jitsi desktop version conferred some benefits compared to the web client. I suppose now I will not know :-(

Ubuntu 18.04, [Jitsi 2.10](https://github.com/jitsi/jitsi/releases/download/Jitsi-2.10/jitsi_2.10.5550-1_amd64.deb). Exactly the same error as for @cast-away, and the splash screen freezes after showing "NimbuzzAvatars".

**Comment by account75783** [comment]
Same issue also using Kubuntu 19.10 :(

**Comment by reini-1** [comment]
As mentioned in #675 (https://github.com/jitsi/jitsi/issues/675), jitsi only works with java 8.

**Comment by jose1711** [comment]
Another workaround (though probably not too safe) for Debian(-based) systems is changing default java version:
```
update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```

Or use nightly which seems to be working the latest OpenJDK.

**Comment by OzoneWebfilter** [comment]
Jitsi doesnt start with NimbuzzAvatars with OpenJdk 11. We need to install Openjdk 8 and set as default..

sudo apt-get install openjdk-8-jdk .
sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
