### ISSUE TITLE
2.9.x.x nightly build ( +possibility for PGP/GPG support? )

### ISSUE THREAD

**Issue by Sanyy** [jitsi/jitsi#256]
- Has no "Create a New XMPP Account" function if you want to add an XMPP account
- In Video Call by switching Full screen ->  menu elements barely visible (~10%,only the top of them can be seen)
Sorry if this is a wrong topic to "cry myself out", in stable release these functions work normally.

One more question:
- Are you planning to implement **PGP/GPG support** for the chat as **Psi+** has?
 I know, some say OTR also a good solution but for me this is the missing part to say: Jitsi is perfect.

**Comment by ibauersachs** [comment]
1) This has been removed because it didn't work properly and had severe security issues.
2) Please send screenshots to the mailing list that compare the working/non-working full screen mode.
3) No, because we don't have resources for it. If someone else wants to contribute it, I'm happy to review a pull request.
