### ISSUE TITLE
On-net static pattern at start of call

### ISSUE THREAD

**Issue by sdaniel1975** [jitsi/jitsi#317]
Hello.  I'm testing Jitsi for SIP calls.  I've noticed that when I call extensions on-net, I get an odd 7 or 8 pulse static pattern at the beginning of each call, only heard on the callee side.  After that initial static pattern, the call is perfect.  If I call over PSTN, there's no issue at all.  What could be causing this?

**Comment by saghul** [comment]
Are you using different codecs for the 2 calls?  Which ones?  Does it happen when you dial any other endpoint / SIP URI?

**Comment by sdaniel1975** [comment]
@saghul 
I figured it out.  It didn't like g722 being enabled.  As soon as I disabled it, the on net calling is working.

**Comment by saghul** [comment]
G722 is a special one. There is a bug in the spec because 14 bits are used for audio samples and some implementations take the first 14 others the last 14 so implementations usually detect the mismatch and adjust accordingly, hence the choppy audio in the beginning.

I guess we can close this now then.

**Comment by sdaniel1975** [comment]
Thanks!!
