### ISSUE TITLE
Application hangs when changing keyboard language while writing in a chat window

### ISSUE THREAD

**Issue by imperative** [jitsi/jitsi#359]
Windows 7 x64.
Jitsi version 2.10.555.0

When I am writing a message in a chat window - if I try to change the system language using the keyboard combination (Alt-Shift, etc), the application completely hangs for at least 1 hour (so indefinitely), and it has to be killed manually.

**Comment by ibauersachs** [comment]
We've hard that before, but could never reproduce it. Some of the developers are from Bulgaria and switch between cyrillic and english regularly. I also tried on Windows 7 and 10 just now and it worked fine, even with LTR-languages and the popups for chinese characters when typing pinyin.

If you have additional language switching tools installed, I can only suggest to try uninstalling them.

**Comment by imperative** [comment]
You close a bug issue just like that? Thank you for your advice, but uninstalled Jitsi instead. If this is your attitude towards obvious bugs (you even write that you have heard about this bug before?), it tells me a lot about developer culture in this project, and it just seems better to switch to and support another messenger, there are tons of them out there now.

**Comment by jitsi-developers** [comment]
On Sunday 02 July 2017 at 20:08:07, Cray Imperative wrote:

> You close a bug issue just like that? Thank you for your advice, but
> uninstalled Jitsi instead. If this is your attitude towards obvious bugs
> (you even write that you have heard about this bug before?), it tells me a
> lot about developer culture in this project, and it just seems better to
> switch to and support another messenger, there are tons of them out there
> now.

Disclaimer - I have no affiliation with the Jitsi developer team.

I wonder:

1. What support have you provided so far to the Jitsi project, which it's 
going to miss out on if you decide to use something else instead?

2. What do you expect the developers to do if they cannot reproduce the 
problem, despite having tried?

3. I notice you initially filed the problem report on 10th May.  A fair amount 
of development has happened since then.  Have you confirmed whether:

a) the problem still exists for you in a current version?

b) you can reproduce it on another computer?


Regards,


Antony.

-- 
Most people are aware that the Universe is big.

 - Paul Davies, Professor of Theoretical Physics

                                                   Please reply to the list;
                                                         please *don't* CC me.
