### ISSUE TITLE
Roster problem with Cisco IM&P servers since 2.8

### ISSUE THREAD

**Issue by npetreley** [jitsi/jitsi#362]
Sometime around the release of 2.8 (sorry, I don’t recall exactly when), Jitsi started failing to load my roster when I log into a Cisco IM&P Jabber server.  You will see from the logs that the request for the roster is refused, and a null pointer exception occurs at org.jivesoftware.smack.AbstractConnection.getRoster(AbstractConnection.java:406).
 
Current OS Windows 10
Jitsi version 2.10 (latest stable x64)
 
Contents of the log directory are attached.
[jitsi.zip](https://github.com/jitsi/jitsi/files/1005257/jitsi.zip)

**Comment by ibauersachs** [comment]
It was introduced in https://github.com/jitsi/smack_3_2_2/commit/2fa36c6a92821ebedc395da75c7a74e2d0cd6c89.

The server violates the current XMPP specification by sending the full JID instead of the bare JID ([RFC 6121, 2.1.6](https://tools.ietf.org/html/rfc6121#section-2.1.6)). However, sending the full JID was allowed in the previous specification, [RFC 3921, 7.2](https://tools.ietf.org/html/rfc3921#section-7).

While we could just allow full JIDs again, it would be better if the server behaved to current standards. I realize this is easier said than done, so I've [asked](https://community.igniterealtime.org/message/265264) the Smack guys what they think about that.
