### ISSUE TITLE
audio device selection problem

### ISSUE THREAD

**Issue by c-alpha** [jitsi/jitsi#364]
_Users mailing list thread: http://lists.jitsi.org/pipermail/users/2017-May/013087.html_

I'm on macOS 10.12.5 and I use [Soundflower](https://github.com/mattingalls/Soundflower) to route audio from VoIP apps (Jitsi, WebEx, and FaceTime) through an audio mixing app. I use two Soundflower instances, one to feed audio to the VoIP app's input (called "Soundflower (2ch)"), and one to capture the VoIP app's output (called "Soundflower (64ch)"). Soundflower is a kernel extension, so in user-land they appear as normal audio devices.

In Jitsi's audio device prefs, both devices appear in the drop-down menus as expected. When I select the 64ch one, the setting flips back top the 2ch one, however. The 2ch device is used fine, and audio flows between it an Jitsi. I just can't get Jitsi to use the 64ch device.

FaceTime and WebEx can use the 64ch device just fine.

**Comment by ibauersachs** [comment]
The problem here is rather complex. Audio devices in a system have a unique identifier. Ideally, Jitsi would simply store this UID to identify devices. This would cause problems with USB devices however, as the UID for such a device includes the physical port it is connected to. If the user connects a headset on a laptop on one port today, and then a different tomorrow, we wouldn't recognize the device anymore.

So Jitsi doesn't store the UID, but the model identifier UID. This should be the same for a device, regardless of where it is connected. But likely also the same if two identical headsets are connected. Which is exactly what happens with the Soundflower driver.

We should store the device UID and then fall back to the model UID if the device cannot be found, as [suggested a long time ago](https://lists.apple.com/archives/coreaudio-api/2005/Sep/msg00217.html). As I don't have a Mac, I cannot work on that.

For reference, the code is in libjitsi: org.jitsi.impl.neomedia.Devices#saveDevice.

I'm closing the issue here, feel free to reopen it in libjitsi (reference this one here). But regardless of where it's filed, it's unlikely to be addressed unless someones from the community creates a patch.
