### ISSUE TITLE
Add version suffixes to software requirements for SUSE packages

### ISSUE THREAD

**Issue by elfring** [jitsi/jitsi#383]
Software requirements for SUSE packages were [updated for one library yesterday](https://github.com/jitsi/jitsi/commit/d9a52ae19507a1f1134db2af6efe901290ec97a7 "Another update for “Requires”").
I find that further software dependencies need similar development considerations.

Package names:
* [java-9-openjdk](https://software.opensuse.org/package/java-9-openjdk "Checking dependencies for OpenJDK runtime environment")
* [libappindicator1](https://github.com/jitsi/jitsi/issues/375#issuecomment-318318146 "Checking dependencies for an application indicators library")
* [libspeex1](https://software.opensuse.org/package/libspeex1 "Checking dependencies for a speech codec library")
* [libspeexdsp1](https://software.opensuse.org/package/libspeexdsp1 "Checking dependencies for a digital signal processor library")

Would you like to take another look at corresponding RPM specifications?

**Comment by ibauersachs** [comment]
I'm closing all RPM issues and we will disable the RPM builds. Once the migration to OpenH264 and Smack 4.2.x is complete, we can reconsider how to proceed with RPMs. If there are public build infrastructures for various systems (Suse, Fedora, etc.) available, we might be able to use those instead of our own - which doesn't scale.
