### ISSUE TITLE
Add changelog to GitHub releases

### ISSUE THREAD

**Issue by baimafeima** [jitsi/jitsi#398]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by ibauersachs** [comment]
The Github 'releases' are a piece of *#&@. Every tag counts as a release and because we tag every build (even rebuilds of the same commit) the list is full of stuff that aren't actual releases. 

We already maintain an official changelog, automstically generated based on the commits for nightly builds an a manually maintened one for stable releases. Aren't these sufficient? At least if they would be somwhat more accessible, e.g. by linking to them from the default readme?

**Comment by baimafeima** [comment]
> because we tag every build (even rebuilds of the same commit) the list is full of stuff that aren't actual releases.
Why would you need to tag every build?

**Comment by ibauersachs** [comment]
Because they are downloadable als snapshots/nightly builds, and we need to cross reference logs from such builds.

**Comment by ibauersachs** [comment]
I've added the changelogs to the Git tags of the official releases (`Jitsi-x.y`) here on Github and will do so for future releases.

**Comment by baimafeima** [comment]
@ibauersachs Thanks a lot, looking awesome now!
