### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by Godrod** [jitsi/jitsi#405]
Is there a chance to get support for discord chat audio and video calls ?

**Comment by ibauersachs** [comment]
It's unclear to me what protocols are being used by Discord. Since the base of the software apparently is Electron, it's likely WebRTC based, but because it's proprietary software, it would require extensive reverse engineering. We cannot look at the libpurple plugin either, since that is GPL licensed.

So in short: sorry, no. (Unless someone from the community steps up, creates a pull request and is committed to maintaining the protocol.)
