### ISSUE TITLE
Problems with DNS

### ISSUE THREAD

**Issue by code-chicken** [jitsi/jitsi#443]
I am using a FreePBX Server on Linux and Jitsi on a connected Windows Machine.
A nslookup request from the windows machine gives the following:
```
C:\Users\r.hahn>nslookup freepbx.starfleet.lan
Server:  andromeda
Address:  192.168.73.1

Name:    freepbx.starfleet.lan
Address:  192.168.73.6
```
From Windows, I can ping the FreeBPX server with the following command:
```
C:\Users\r.hahn>ping freepbx.starfleet.lan

Pinging freepbx.starfleet.lan [192.168.73.6] with 32 bytes of data:
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
```
I can - of course -also ping the server using its IP:
```
C:\Users\r.hahn>ping 192.168.73.6

Pinging 192.168.73.6 with 32 bytes of data:
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
Reply from 192.168.73.6: bytes=32 time<1ms TTL=64
```
However, if I enter the following SIP address in Jitsi I cannot connect to the server:
`31@freepbx.starfleet.lan`

Everything is fine if I enter the IP address::
`31@192.168.73.6`

I am not sure about the configuration within Jitsi. Maybe I have to use special settings?

**Comment by code-chicken** [comment]
It seems that somehow everythings is working now. Maybe it was an incorrect SRV entry for SIP services that I deleted today.

**Comment by code-chicken** [comment]
Unfortunately I had to realize that the problem was **not** solved. Actually I cannot connect to our freepbx server using its name when at the same time there is a VPN connection active.
So it must have something to do with the Jitsi way of resolving DNS because I can reach the server using other standard tools as you can see above.
Also I can connect to the freepbx server using PhonerLite (another SIP communication program for Windows).

**Comment by ibauersachs** [comment]
Can you please try to disable the parallel DNS resolver (Tools->Options->Advanced->DNS)?

Is the name of the FreePBX server resolvable on the DNS servers supplied by the VPN connection? If not, then there's nothing we can do while the VPN connection is active.

A little background: Java implements its own DNS resolving and does not use the underlying OS mechanisms at all. It also has bugs in enumerating the DNS servers used by the OS (it does registry lookups instead of using APIs) and can find DNS servers of inactive connection (e.g. on notebooks connected via cable and a disconnected WiFi).
Then there's the changes of Windows 10: ping/nslookup etc. try to resolve a server name using all available DNS servers, even when a VPN connection is active. This often leads to unwanted DNS leaks, but in your case, it might be the reason why you can resolve the name even when the VPN is active.

**Comment by code-chicken** [comment]
Hi Ingo,

maybe I was a little bit unclear about the VPN connection. Of course our FreePBX-Server ist not resolvable on the DNS-Servers supplied by the VPN Connection. We just sometimes use VPN (i.e. OpenVPN) to support some of our customers with their IT.

However, as soon as we create a VPN connection it seems that Jitsi is not able to resolve our internal FreePBX server any more. As you already explained, the reason for this indeed might be that Java has different mechanisms to resolve domain names. Unfortunately.

Thank you anyway.

**Comment by ibauersachs** [comment]
Well, this is somewhat expected then. DNS wasn't meant to be ambiguous (i.e. one server returning not found, one having an answer), the only time multiple servers are contacted is a query fails.

Workarounds:
- Make your PBX server name publically resolvable
- Use the PBX server's IP address in the account configuration
