### ISSUE TITLE
Proper Debian packages

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi#460]
Please put your packages directly on Debian so one can just use apt-get to install them.
If every package needed remote instructions like https://jitsi.org/downloads/
the world would not be a fun place.

**Comment by damencho** [comment]
You know that last time we tried pushing jitsi desktop there it took 6 months for one dev to do it. And with all these js dependencies I estimate it on 2 years now :) 
So any help is welcome, but currently we do not have such a plan, but will review any contributions on the subject.

**Comment by jidanni** [comment]
You need your own Debian Developer to do it.
Have one of your team become a Debian Developer.

**Comment by saghul** [comment]
@jidanni This is the second time I've seen you (try to) tell us what to do just because you'd like it that way. I don't appreciate the tone a single bit.

All feedback is of course welcome, but you have to accept that the answer might be "no" and you can do one of two things: try to be more persuasive, or understand that the project's priorities / interests might not be aligned with yours. Being pushy doesn't help at all.

Anyone can push a package onto Debian, if they are willing to put in the effort. As Damyan said past efforts weren't positive, so it's not something we are going to tackle ourselves. If you are so inclined, feel free to file an ITP and see the process through.

**Comment by ibauersachs** [comment]
Duplicate of #198
