### ISSUE TITLE
Disable video popup when jitsi not in focus

### ISSUE THREAD

**Issue by kflak** [jitsi/jitsi#672]
I work with swaywm, a tiling window manager on Linux, and it is incredibly confusing and annoying when a new video window opens up every time I change focus. Is there a way to disable this? I understand the rationale for this on a "regular" desktop manager, but it doesn't work at all on a tiling manager: the popup window becomes as large as the original window, messing up the entire screen layout.

**Comment by mlncn** [comment]
Yes please!  This is very frustrating on Jitsi Desktop, also on Ubuntu with default window manager.

1. Alt-Tab away from Jitsi to look at another Window.  The Jitsi mini video overlay has stolen focus, you can't type.
2. Or if you didn't try to type, and just read something in the other window, when you Alt-Tab to go back to Jitsi... you stay where you were, because the Jitsi video pop-up is where you are alt-tabbing from, so you end up at the application you were trying to leave.

An option to disable this is really needed.

**Comment by mptpro** [comment]
Same issue. Everytime I do a screen share, then want to come back to Jitsi by using Alt+Tab the mini-player pops-up instead of the the "full" Jitsi window. I have to double-click the mini player to get back to Jitsi.  I switch between screen sharing and web cam often during a meeting, sometimes more than 20 times.  Can we just disable the mini-player pop-up all together?

**Comment by dfhssilva** [comment]
I also suffer from the same issue. An option to turn this feature off would be really appreciated!

**Comment by Half-Shot** [comment]
FTR https://community.jitsi.org/t/how-to-disable-popup-video-window/109169/2 seems to answer this one

**Comment by kflak** [comment]
Thanks, @Half-Shot! That solves the problem!

**Comment by 10leej** [comment]
This issue has returned, there is no apparent option to disable the popup.
Rather than opening a new issue can we reopen this one as it's now relavent?

**Comment by quite** [comment]
Agreed. This popup is troublesome, possibly especially in tiling desktops. To be clear, the following is no longer a solution, the gui has changed, option gone: ~~https://community.jitsi.org/t/how-to-disable-popup-video-window/109169/2~~

**Comment by saghul** [comment]
<img width="1008" alt="Screen Shot 2023-09-18 at 14 55 10" src="https://github.com/jitsi/jitsi/assets/317464/88140afd-2002-49c8-8e23-f0cbfea4ec8e">

It's still there.
